### ISSUE TITLE
Action breaks when a user is invited more than once

### ISSUE THREAD

**Issue by jschanfung** [icub-tech-iit/outside-collaborators#13]
Hey I found this solution is very helpful! One thing I want to check is when you have multiple group permissions for a single repo, do you have to ensure a given user must only present in one group? Taking the README example:
```yaml
lab_xyz/group01:
  - "user01"
  - "user02"
  - "user03"

lab_xyz/group02:
  - "user04"
  - "user05"
  - "user06"
```
If you got group02 like this instead:
```yaml
lab_xyz/group02:
  - "user03"
  - "user04"
  - "user05"
  - "user06"
```
while having something like this for your repo
```yaml
repo_name_1:
  lab_xyz/group01:
    type: "group"
    permission: "read"

  lab_xyz/group02:
    type: "group"
    permission: "triage"
```
You will likely get an error message like:
```
/var/lib/gems/2.5.0/gems/octokit-4.19.0/lib/octokit/response/raise_error.rb:16:in `on_complete': PATCH https://api.github.com/repos/somerepo/oc-test-4/invitations/33467263: 422 - Invalid request. (Octokit::UnprocessableEntity)
```
I wonder if this is a limitation that the solution does not support sending invitation twice for a single user during one workflow  run. It is not a blocker to me so just want to clarify a bit
