### ISSUE TITLE
Handle Rate Limit

### ISSUE THREAD

**Issue by pattacini** [icub-tech-iit/outside-collaborators#22]
Instead of letting the action fail because of having hit the rate limit, we may consider handling it through suitable wait states by reading relevant info via the API.

See:
- https://octokit.github.io/octokit.rb/Octokit/Client/RateLimit.html
- https://octokit.github.io/octokit.rb/Octokit/RateLimit.html

**Comment by pattacini** [comment]
Done in #24 ✔

**Comment by JeroenKnoops** [comment]
@pattacini FYI

Although this solution works, I have changed the workflow a little bit, and instead of using a PAT, we're now using a github app to do all the API calls.

We've used something similar to: https://github.com/peter-murray/workflow-application-token-action

You can grant the exact permissions to an app, and with the workflow-application-token-action you can get a temporary token to do all API calls. This will no longer case any rate limit to be hit since the number is set a lot higher for apps.

See: https://docs.github.com/en/developers/apps/rate-limits-for-github-apps

Workflow will look something like:
```
      - uses: peter-murray/workflow-application-token-action@v1
        name: Retrieve App Token
        id: app_token
        with:
          application_id: ${{ secrets.APP_ID }}
          application_private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Outside collaborators
        run: |
          cd scripts
          ./outside-collaborators-handler.rb
        env:
          OUTSIDE_COLLABORATORS_GITHUB_ORG: ${{ github.repository_owner }}
          OUTSIDE_COLLABORATORS_GITHUB_TOKEN: $ {{ steps.app_token.outputs.token }}
```

I can't really make a PR, because without creating an app it's hard to tell if it works in your case.
