### ISSUE TITLE
Add collaborators to a list of repos

### ISSUE THREAD

**Issue by TimPietrusky** [icub-tech-iit/outside-collaborators#51]
It would be really nice if we could add a list of collaborators to a list of repos, so that we don't have to copy the same block over and over again:

```yaml
repoA:
  groupC:
    type: "group"
    permissions: "read"
  userC:
    type: "user"
    permissions: "write"

repoB:
  groupC:
    type: "group"
    permissions: "read"
  userC:
    type: "user"
    permissions: "write"
```

Is this already possible? I couldn't figure it out, as this wasn't working:

```yaml
repoA:
repoB:
  groupC:
    type: "group"
    permissions: "read"
  userC:
    type: "user"
    permissions: "write"
```

**Comment by pattacini** [comment]
Hi @TimPietrusky 

Thanks for reaching out!

This wasn't a feature I had in mind when I coded this automation. I believe it needs a bit of rework but it should be doable.
I'll put it on my list and be on it as soon as possible.

Thanks for the nice suggestion 👍🏻

**Comment by pattacini** [comment]
Hi @TimPietrusky 

I've collected some info on [YAML anchors and aliases][1] and it looks that the following should do the job:

```yaml
repoA: &template
  groupC:
    type: "group"
    permissions: "read"
  userC:
    type: "user"
    permissions: "write"

repoB:
  <<: *template
```

Could you give it a whirl?

[1]: https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd
